'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const roles={
 insurer:{kicker:'CONTINUITY BETWEEN SITE VISITS',title:'Know what changed since your last inspection.',description:'Receive a site-specific prevention profile that connects open findings, corrective actions and supporting evidence. Use it to prepare inspections and focus preventive support.',list:['One view of recurring issues and overdue actions','Evidence-linked follow-up with risk engineers','Insurer-funded access for participating sites'],cta:'Check insurer pilot fit',title2:'Portfolio overview',labels:['Pilot sites','Open actions','Ready for review'],values:['3','7','2'],table:'Participating site',rows:[['North Plant','Machining','Check new evidence','Needs review','warning'],['Valley Works','Assembly','Independent check','Ready for review','ready'],['West Manufacturing','Production','Track recurrence','Checked','done']],note:'Agreed prevention evidence. No pricing or claims decisions in the pilot.'},
 manufacturer:{kicker:'A PRACTICAL PATH TO CLOSURE',title:'Give your team a clear next action.',description:'Get engineering-reviewed recommendations, document corrective actions and make your prevention work visible. The proposed model includes insurer-funded software access.',list:['Prioritised guidance and pilot peer comparisons','A documented proof-of-prevention record','No separate software fee; implementation costs remain'],cta:'Check manufacturing pilot fit',title2:'Site action workspace',labels:['Open actions','Awaiting evidence','Ready for review'],values:['4','2','1'],table:'Equipment',rows:[['CNC-04','Maintenance','Engineering review','Needs review','warning'],['Assembly-02','Action evidence','Send for review','Ready for review','ready'],['Cooling-01','Implementation','Monitor recurrence','Checked','done']],note:'Your team chooses and implements measures. Operational effort still applies.'},
 verifier:{kicker:'INDEPENDENCE WITH CONTEXT',title:'Review the work. Record what is known.',description:'Access a defined review scope, inspect the supporting evidence and document findings and limitations.',list:['See the original finding and agreed action','Request additional evidence where needed','Record the scope and limits of each review'],cta:'Check verification pilot fit',title2:'Verification workspace',labels:['Assigned reviews','Evidence requests','Checks recorded'],values:['3','1','1'],table:'Review case',rows:[['CNC-04','Review not started','Wait for evidence','Pending','warning'],['Assembly-02','Agreed scope','Review records','Ready for review','ready'],['Cooling-01','Review recorded','Report limitations','Checked','done']],note:'Checking implementation does not establish long-term effectiveness.'}
};
function setRole(key){const r=roles[key];$$('[data-role]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.role===key)));$('#role-kicker').textContent=r.kicker;$('#role-title').textContent=r.title;$('#role-description').textContent=r.description;$('#role-list').innerHTML=r.list.map(v=>'<li>'+v+'</li>').join('');$('#role-cta').innerHTML=r.cta+' <span>↗</span>';$('#dash-title').textContent=r.title2;$('#table-name').textContent=r.table;$('#metrics').innerHTML=r.values.map((v,i)=>'<div class="metric"><strong>'+v+'</strong><span>'+r.labels[i]+'</span></div>').join('');$('#dash-rows').innerHTML=r.rows.map(v=>'<div class="data-row"><div><strong>'+v[0]+'</strong><small>'+v[1]+'</small></div><span>'+v[2]+'</span><span class="status '+v[4]+'">'+v[3]+'</span></div>').join('');$('#dash-note').textContent=r.note;$('#pilot-form select').value={insurer:'Industrial insurer',manufacturer:'Manufacturing company',verifier:'Verification partner'}[key];}
$$('[data-role]').forEach(b=>b.addEventListener('click',()=>setRole(b.dataset.role)));setRole('insurer');
const findings=[
 {title:'A pattern worth investigating.',status:'Needs review',cls:'warning',desc:'Three maintenance entries describe coolant leakage at CNC-04. An engineer needs to assess the recurring issue.',owner:'Maintenance engineer',next:'Review the maintenance history',source:'Maintenance records',evidence:'3 linked maintenance entries',sub:'Illustrative records · No live data'},
 {title:'The action is ready for a closer look.',status:'Ready for review',cls:'ready',desc:'The assembly team has documented a completed maintenance action. The agreed evidence is ready for independent review.',owner:'Independent verifier',next:'Check evidence against scope',source:'Action record and photos',evidence:'Completion record + 2 photos',sub:'Implementation reported · Not yet checked'},
 {title:'Implementation checked. Follow-up continues.',status:'Checked',cls:'done',desc:'A cooling-system measure has been checked against its agreed scope. Effectiveness still needs observation over time.',owner:'Site maintenance lead',next:'Monitor reported recurrence',source:'Independent review record',evidence:'Review report + stated limitations',sub:'Implementation checked · Effect unproven'}
];
window.selectedFinding=0;
function selectFinding(i){window.selectedFinding=i;const f=findings[i];$('#finding-count').textContent='0'+(i+1)+' / 03';$('#finding-status').textContent=f.status;$('#finding-status').className='status '+f.cls;$('#finding-title').textContent=f.title;$('#finding-description').textContent=f.desc;$('#finding-details').innerHTML=[['Source',f.source],['Accountable role',f.owner],['Next step',f.next]].map(r=>'<div><dt>'+r[0]+'</dt><dd>'+r[1]+'</dd></div>').join('');$('#finding-evidence').textContent=f.evidence;$('#finding-source').textContent=f.sub;$$('[data-finding]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.finding)===i)));$('#follow-finding').innerHTML=(i===0?'Follow this finding':'Explore the CNC example')+' <span>→</span>';if(window.renderFactory)window.renderFactory();}
window.selectFinding=selectFinding;$$('[data-finding]').forEach(b=>b.addEventListener('click',()=>selectFinding(Number(b.dataset.finding))));selectFinding(0);
const steps=[
 {owner:'DETECT / SENTINELAI',title:'Connect the signals in the records.',desc:'A recurring coolant leak appears in three CNC-04 maintenance entries. SentinelAI brings the records together for engineering review.',state:'Needs review',cls:'warning',entries:[['01','Maintenance entry · 04 Sep','Coolant leakage reported. Area cleaned and finding recorded.'],['02','Maintenance entry · 11 Sep','Leak reported again. Earlier entry linked.'],['03','Maintenance entry · 18 Sep','A recurring pattern is flagged for the maintenance engineer.']]},
 {owner:'PRESCRIBE / SENTINELAI + QUALIFIED ENGINEER',title:'Recommend a fix. Get engineering sign-off.',desc:'The site engineer reviews the context and assesses a suggested investigation. The engineer decides the appropriate work and its safe execution.',state:'Action agreed',cls:'ready',entries:[['✓','Engineering review','Check the source of the recurring leak under the site’s approved maintenance procedures.'],['→','Assigned owner','Site maintenance lead. Scope and resources agreed before work.'],['↗','Evidence requested','Record the work performed and relevant follow-up observations.']]},
 {owner:'FIX / MANUFACTURING TEAM',title:'Do the work. Keep the evidence.',desc:'The maintenance team implements the agreed action and documents the work. Try adding a sample completion record to the demo.',state:'In progress',cls:'warning',entries:[['✓','Action accepted','The site has assigned the maintenance work.'],['…','Completion evidence','Awaiting the site’s work record. Adding evidence prepares a review; it does not verify the action.']],action:true},
 {owner:'VERIFY / INDEPENDENT SPECIALIST',title:'Check implementation against the scope.',desc:'The independent specialist reviews selected measures and available evidence. The report distinguishes what was checked from what remains uncertain.',state:'Review recorded',cls:'done',entries:[['✓','Agreed scope','Check the documented corrective action and selected supporting evidence.'],['✓','Illustrative review result','Implementation recorded as consistent with the agreed scope.'],['!','Limitation','This review does not establish a reduction in long-term failure or loss frequency.']]},
 {owner:'CREDIT / FUTURE INSURER DECISION',title:'Build the evidence for future incentives.',desc:'The pilot creates a proof-of-prevention record. The longer-term model explores insurer-agreed premium credits for verified improvements. No credit is automatic or included in the pilot.',state:'Future model',cls:'neutral',entries:[['✓','Pilot output: proof of prevention','The finding, action and review are linked for agreed sharing and follow-up.'],['→','Future hypothesis: credits, not penalties','An insurer could recognise verified improvements with agreed incentives. The model and evidence requirements still need validation.'],['i','Current pilot boundary','No premium credits or use of pilot outputs for pricing, coverage or claims decisions.']]}
];
let currentStep=0,evidenceAdded=false;
function setStep(n){currentStep=n;const detectEvidence=document.getElementById('detect-evidence');if(detectEvidence)detectEvidence.hidden=n!==0;const workflowBody=document.querySelector('.workflow-body');if(workflowBody)workflowBody.classList.toggle('detect-mode',n===0);const s=steps[n];$$('[data-step]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.step)===n)));$('#step-owner').textContent=s.owner;$('#step-title').textContent=s.title;$('#step-description').textContent=s.desc;$('#record-state').textContent=n===2&&evidenceAdded?'Ready for review':s.state;$('#record-state').className='status '+(n===2&&evidenceAdded?'ready':s.cls);$('#step-progress').textContent=(n+1)+' of 5';$('#prev-step').disabled=n===0;$('#next-step').textContent=n===4?'Start again ↺':'Next step →';let entries=s.entries;if(n===2&&evidenceAdded)entries=[s.entries[0],['✓','Sample completion record attached','Site reports action completed. Independent review remains pending.']];$('#record-content').innerHTML=entries.map(r=>'<div class="record-entry"><span>'+r[0]+'</span><div><strong>'+r[1]+'</strong><p>'+r[2]+'</p></div></div>').join('')+(s.action?'<button class="record-action" id="add-evidence">'+(evidenceAdded?'Remove sample evidence':'＋ Add sample completion evidence')+'</button>':'');if(s.action)$('#add-evidence').addEventListener('click',()=>{evidenceAdded=!evidenceAdded;setStep(2);});}
$$('[data-step]').forEach(b=>b.addEventListener('click',()=>setStep(Number(b.dataset.step))));$('#prev-step').addEventListener('click',()=>setStep(Math.max(0,currentStep-1)));$('#next-step').addEventListener('click',()=>setStep((currentStep+1)%5));$('#follow-finding').addEventListener('click',()=>{setStep(0);$('#workflow').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});});setStep(0);
const menu=$('.menu-toggle');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));$('#navlinks').classList.toggle('open',open);});$$('#navlinks a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');$('#navlinks').classList.remove('open');}));
$$('[data-pilot]').forEach(b=>b.addEventListener('click',()=>{if(b.id==='role-cta'){$('#pilot').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}else{$('#pilot-dialog').showModal();}}));$('#open-notice').addEventListener('click',()=>$('#notice-dialog').showModal());$$('.close-dialog').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
$('#pilot-form').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.target);const body='SENTINELAI — PILOT DISCUSSION BRIEF\n\nName: '+fd.get('name')+'\nWork email: '+fd.get('email')+'\nCompany: '+fd.get('company')+'\nPerspective: '+fd.get('role')+'\n\nWhat I would like to explore:\n'+fd.get('message')+'\n\nPrepared locally. This enquiry has not been sent.\n';const url=URL.createObjectURL(new Blob([body],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='SentinelAI-pilot-brief.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#form-result').textContent='Pilot brief prepared for download. Share it with your SentinelAI contact; nothing has been sent.';});
